### ISSUE TITLE
[security] path disclosure

### ISSUE THREAD

**Issue by nixawk** [ctubio/php-proxy-keyserver#1]
Please search the keyword **evil**, **pgp.key-server.io** shows an path disclosure error as follow. 

> https://pgp.key-server.io/pks/lookup?search=evil&fingerprint=on&op=vindex

```
Unknown skin path: "../skin/default/plain_errors/504.phtml".
#0 /var/www/pgp.key-server.io/src/ctubio/HKPProxy/Keyserver/Skin/Content.php(25): ctubio\HKPProxy\Keyserver\Skin\Content->parsePhtml('../skin/default...')
#1 /var/www/pgp.key-server.io/src/ctubio/HKPProxy/Keyserver/Skin.php(38): ctubio\HKPProxy\Keyserver\Skin\Content->__toString()
#2 /var/www/pgp.key-server.io/src/ctubio/HKPProxy/Keyserver/Skin.php(24): ctubio\HKPProxy\Keyserver\Skin::parseNonPhtml(Object(Symfony\Component\HttpFoundation\Response), '/errors/504')
#3 /var/www/pgp.key-server.io/src/ctubio/HKPProxy/Keyserver/Router.php(18): ctubio\HKPProxy\Keyserver\Skin::parsePhtml(Object(Symfony\Component\HttpFoundation\Response), '/errors/504')
#4 /var/www/pgp.key-server.io/src/ctubio/HKPProxy/Keyserver.php(19): ctubio\HKPProxy\Keyserver\Router::getResponse()
#5 /var/www/pgp.key-server.io/pub/php-proxy-keyserver.php(14): ctubio\HKPProxy\Keyserver::getResponse()
#6 {main}
```

**Comment by ctubio** [comment]
Im sorry i couldnt reproduce this error, I just clicked (5min after you) that link and it returned a normal webpage (see image attached).

Thank you for report this, but this is expected behaviour (see https://github.com/ctubio/php-proxy-keyserver/blob/master/pub/php-proxy-keyserver.php#L4-L5).

![evit](https://cloud.githubusercontent.com/assets/1634027/16508499/c2223b26-3f33-11e6-86c1-a940cef6999b.png)

**Comment by nixawk** [comment]
@ctubio If I use safari, everything goes well. Please try it with chrome - `Version 51.0.2704.103 (64-bit)`.

<img width="1261" alt="screen shot 2016-06-30 at 19 39 15" src="https://cloud.githubusercontent.com/assets/7352479/16508635/758ab204-3efa-11e6-907e-c4aed83575f2.png">

**Comment by ctubio** [comment]
i cant reproduce it :sob:, but i will add a 504.phtml file to handle gateway timeout errors, that currently are out-of-control as you discovered.

Thank you'¡ (will fix in next commit)

**Comment by nixawk** [comment]
OK, thanks.
