### ISSUE TITLE
Add peer membership HTML validation error

### ISSUE THREAD

**Issue by inpos** [ctubio/php-proxy-keyserver#3]
On successful save membership-line "HTML validation error" page return.
If comment HTML validation block in php-code then empty page return.
But membership-line is added in /etc/sks/membership

**Comment by ctubio** [comment]
:pencil2: ima leave this here:
```
Validation of Strict HTML failed:
	Opening and ending tag mismatch: small line 47 and div

	Opening and ending tag mismatch: div line 22 and body

	Opening and ending tag mismatch: body line 13 and html

	Premature end of data in tag html line 2
```

**Comment by ctubio** [comment]
Many thanks for the bug report inpos'¡
will fix in next commit :sob:

**Comment by inpos** [comment]
It's very useful feature.
I'm surprised that no one has reported the problem

**Comment by inpos** [comment]
New validation error:
```
<pre>Validation of Strict HTML failed:
	Opening and ending tag mismatch: div line 14 and body

	Opening and ending tag mismatch: body line 13 and html

	Premature end of data in tag html line 2
</pre>
```

**Comment by inpos** [comment]
I did the following steps:
`git pull`
`composer update`

**Comment by inpos** [comment]
Can you change '\n' (newline symbol) location in saved membership-line?
Move it from start of line to the end.

**Comment by ctubio** [comment]
The official distributed membership file does not end with newline char, so be aware **first saved item may fail**; but i agree newline should be at the end, so lets apply it and hope for the distributed file to be fixed someday too (https://bitbucket.org/skskeyserver/sks-keyserver/src/85e91d50955ddf982d465443513345f79c372860/sampleConfig/membership?at=default&fileviewer=file-view-default).

**Comment by inpos** [comment]
How about [this](https://github.com/ctubio/php-proxy-keyserver/issues/3#issuecomment-277920277)?

**Comment by ctubio** [comment]
i was not able to reproduce it yet, maybe you have some example of input data that becomes into this error? meanwhile i keep trying to reproduce it somehow :sob:

**Comment by inpos** [comment]
here membership-line:
[copied, thanks!]

**Comment by ctubio** [comment]
mm.. im not sure where is the problem, the membership line of Andrés doesn't give me an error, do you know how i may be able to reproduce this?

i get the following:
![strict_html](https://cloud.githubusercontent.com/assets/1634027/22800701/7a3c53aa-ef0a-11e6-931b-bc827d0f0412.png)

**Comment by inpos** [comment]
This error occurs only after successful adding.
Try to delete line from your membership file and add it using this form

**Comment by inpos** [comment]
I confirm fix.

**Comment by inpos** [comment]
Thanx
