### ISSUE TITLE
UI rendering breaks key server API

### ISSUE THREAD

**Issue by wiegelmann** [ctubio/php-proxy-keyserver#5]
The &options=mr renders a machine-readable version to use it for API calls. The php-proxy-keyserver overnights this method, hence the injection of HTML strings into the rending.

https://pgp.key-server.io/pks/lookup?op=vindex&search=0x0caf1e5b11489a1f&fingerprint=on&options=mr

The correct version should look like this:

http://sks.hnet.se:11371/pks/lookup?op=vindex&search=0x0caf1e5b11489a1f&fingerprint=on&options=mr

**Comment by ctubio** [comment]
oh iSee, should be a downloadable resource instead of a html page; many thanks for explaining it'¡ will try to fix soOn''

**Comment by ctubio** [comment]
sorry i just remembered, the machine-readable output on my keyserver contains HTML output **only if** the connection contains a header of USER_AGENT see
https://github.com/ctubio/php-proxy-keyserver/blob/cf271f17f5bb7f1ff9a08442318737e413cefacf/src/ctubio/HKPProxy/Keyserver/Skin.php#L74

that means that gpg clients will not get HTML (cos they dont send user agent strings), but chromes and mozillas for example will get HTML

it can be tested with:
```
curl -A "" "https://pgp.key-server.io/pks/lookup?op=vindex\&search=0x0caf1e5b11489a1f\&fingerprint=on\&options=mr"
```

or:
```
gpg --keyserver pgp.key-server.io --search 0x0caf1e5b11489a1f
```

hope you agree to close this issue''
thank you for the report''
